/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Asteron
 * Novel writing tool
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  CollectionCreateDto,
  CollectionGetDto,
  CollectionPatchDto
} from '.././models'



/**
 * GET `/collections` Get all collections
 */
export const collectionsControllerGetAll = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CollectionGetDto[]>> => {
    
    return axios.default.get(
      `/api/collections`,options
    );
  }


export const getCollectionsControllerGetAllQueryKey = () => {
    return [`/api/collections`] as const;
    }

    
export const getCollectionsControllerGetAllQueryOptions = <TData = Awaited<ReturnType<typeof collectionsControllerGetAll>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof collectionsControllerGetAll>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCollectionsControllerGetAllQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof collectionsControllerGetAll>>> = ({ signal }) => collectionsControllerGetAll({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof collectionsControllerGetAll>>, TError, TData> & { queryKey: QueryKey }
}

export type CollectionsControllerGetAllQueryResult = NonNullable<Awaited<ReturnType<typeof collectionsControllerGetAll>>>
export type CollectionsControllerGetAllQueryError = AxiosError<unknown>


export function useCollectionsControllerGetAll<TData = Awaited<ReturnType<typeof collectionsControllerGetAll>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof collectionsControllerGetAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof collectionsControllerGetAll>>,
          TError,
          TData
        > , 'initialData'
      >, axios?: AxiosRequestConfig}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useCollectionsControllerGetAll<TData = Awaited<ReturnType<typeof collectionsControllerGetAll>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof collectionsControllerGetAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof collectionsControllerGetAll>>,
          TError,
          TData
        > , 'initialData'
      >, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useCollectionsControllerGetAll<TData = Awaited<ReturnType<typeof collectionsControllerGetAll>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof collectionsControllerGetAll>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }

export function useCollectionsControllerGetAll<TData = Awaited<ReturnType<typeof collectionsControllerGetAll>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof collectionsControllerGetAll>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getCollectionsControllerGetAllQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * GET `/collections/mine` Get my collections
 */
export const collectionsControllerGetMyCollection = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CollectionGetDto[]>> => {
    
    return axios.default.get(
      `/api/collections/mine`,options
    );
  }


export const getCollectionsControllerGetMyCollectionQueryKey = () => {
    return [`/api/collections/mine`] as const;
    }

    
export const getCollectionsControllerGetMyCollectionQueryOptions = <TData = Awaited<ReturnType<typeof collectionsControllerGetMyCollection>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof collectionsControllerGetMyCollection>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCollectionsControllerGetMyCollectionQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof collectionsControllerGetMyCollection>>> = ({ signal }) => collectionsControllerGetMyCollection({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof collectionsControllerGetMyCollection>>, TError, TData> & { queryKey: QueryKey }
}

export type CollectionsControllerGetMyCollectionQueryResult = NonNullable<Awaited<ReturnType<typeof collectionsControllerGetMyCollection>>>
export type CollectionsControllerGetMyCollectionQueryError = AxiosError<unknown>


export function useCollectionsControllerGetMyCollection<TData = Awaited<ReturnType<typeof collectionsControllerGetMyCollection>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof collectionsControllerGetMyCollection>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof collectionsControllerGetMyCollection>>,
          TError,
          TData
        > , 'initialData'
      >, axios?: AxiosRequestConfig}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useCollectionsControllerGetMyCollection<TData = Awaited<ReturnType<typeof collectionsControllerGetMyCollection>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof collectionsControllerGetMyCollection>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof collectionsControllerGetMyCollection>>,
          TError,
          TData
        > , 'initialData'
      >, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useCollectionsControllerGetMyCollection<TData = Awaited<ReturnType<typeof collectionsControllerGetMyCollection>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof collectionsControllerGetMyCollection>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }

export function useCollectionsControllerGetMyCollection<TData = Awaited<ReturnType<typeof collectionsControllerGetMyCollection>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof collectionsControllerGetMyCollection>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getCollectionsControllerGetMyCollectionQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * GET `/collections/:collectionId` Get a single collection's information
 */
export const collectionsControllerGetCollection = (
    collectionId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CollectionGetDto>> => {
    
    return axios.default.get(
      `/api/collections/${collectionId}`,options
    );
  }


export const getCollectionsControllerGetCollectionQueryKey = (collectionId: string,) => {
    return [`/api/collections/${collectionId}`] as const;
    }

    
export const getCollectionsControllerGetCollectionQueryOptions = <TData = Awaited<ReturnType<typeof collectionsControllerGetCollection>>, TError = AxiosError<void>>(collectionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof collectionsControllerGetCollection>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCollectionsControllerGetCollectionQueryKey(collectionId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof collectionsControllerGetCollection>>> = ({ signal }) => collectionsControllerGetCollection(collectionId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(collectionId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof collectionsControllerGetCollection>>, TError, TData> & { queryKey: QueryKey }
}

export type CollectionsControllerGetCollectionQueryResult = NonNullable<Awaited<ReturnType<typeof collectionsControllerGetCollection>>>
export type CollectionsControllerGetCollectionQueryError = AxiosError<void>


export function useCollectionsControllerGetCollection<TData = Awaited<ReturnType<typeof collectionsControllerGetCollection>>, TError = AxiosError<void>>(
 collectionId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof collectionsControllerGetCollection>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof collectionsControllerGetCollection>>,
          TError,
          TData
        > , 'initialData'
      >, axios?: AxiosRequestConfig}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useCollectionsControllerGetCollection<TData = Awaited<ReturnType<typeof collectionsControllerGetCollection>>, TError = AxiosError<void>>(
 collectionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof collectionsControllerGetCollection>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof collectionsControllerGetCollection>>,
          TError,
          TData
        > , 'initialData'
      >, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useCollectionsControllerGetCollection<TData = Awaited<ReturnType<typeof collectionsControllerGetCollection>>, TError = AxiosError<void>>(
 collectionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof collectionsControllerGetCollection>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }

export function useCollectionsControllerGetCollection<TData = Awaited<ReturnType<typeof collectionsControllerGetCollection>>, TError = AxiosError<void>>(
 collectionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof collectionsControllerGetCollection>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getCollectionsControllerGetCollectionQueryOptions(collectionId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * PATCH `/collections/:collectionId` Update a collection (mine or admin only)
 */
export const collectionsControllerUpdateCollection = (
    collectionId: string,
    collectionPatchDto: CollectionPatchDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CollectionGetDto>> => {
    
    return axios.default.patch(
      `/api/collections/${collectionId}`,
      collectionPatchDto,options
    );
  }



export const getCollectionsControllerUpdateCollectionMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof collectionsControllerUpdateCollection>>, TError,{collectionId: string;data: CollectionPatchDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof collectionsControllerUpdateCollection>>, TError,{collectionId: string;data: CollectionPatchDto}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof collectionsControllerUpdateCollection>>, {collectionId: string;data: CollectionPatchDto}> = (props) => {
          const {collectionId,data} = props ?? {};

          return  collectionsControllerUpdateCollection(collectionId,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CollectionsControllerUpdateCollectionMutationResult = NonNullable<Awaited<ReturnType<typeof collectionsControllerUpdateCollection>>>
    export type CollectionsControllerUpdateCollectionMutationBody = CollectionPatchDto
    export type CollectionsControllerUpdateCollectionMutationError = AxiosError<unknown>

    export const useCollectionsControllerUpdateCollection = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof collectionsControllerUpdateCollection>>, TError,{collectionId: string;data: CollectionPatchDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof collectionsControllerUpdateCollection>>,
        TError,
        {collectionId: string;data: CollectionPatchDto},
        TContext
      > => {

      const mutationOptions = getCollectionsControllerUpdateCollectionMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * DELETE `/collections/:collectionId` Delete a collection
 */
export const collectionsControllerDeleteCollection = (
    collectionId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CollectionGetDto>> => {
    
    return axios.default.delete(
      `/api/collections/${collectionId}`,options
    );
  }



export const getCollectionsControllerDeleteCollectionMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof collectionsControllerDeleteCollection>>, TError,{collectionId: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof collectionsControllerDeleteCollection>>, TError,{collectionId: string}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof collectionsControllerDeleteCollection>>, {collectionId: string}> = (props) => {
          const {collectionId} = props ?? {};

          return  collectionsControllerDeleteCollection(collectionId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CollectionsControllerDeleteCollectionMutationResult = NonNullable<Awaited<ReturnType<typeof collectionsControllerDeleteCollection>>>
    
    export type CollectionsControllerDeleteCollectionMutationError = AxiosError<unknown>

    export const useCollectionsControllerDeleteCollection = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof collectionsControllerDeleteCollection>>, TError,{collectionId: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof collectionsControllerDeleteCollection>>,
        TError,
        {collectionId: string},
        TContext
      > => {

      const mutationOptions = getCollectionsControllerDeleteCollectionMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * POST `/collections/create`
Create a collection in our backend, (NOT) in the Firebase
Please be careful with this API call
(though the Firebase collection creation happends automatically when they first log in)
 */
export const collectionsControllerCreateCollection = (
    collectionCreateDto: CollectionCreateDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CollectionGetDto>> => {
    
    return axios.default.post(
      `/api/collections/create`,
      collectionCreateDto,options
    );
  }



export const getCollectionsControllerCreateCollectionMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof collectionsControllerCreateCollection>>, TError,{data: CollectionCreateDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof collectionsControllerCreateCollection>>, TError,{data: CollectionCreateDto}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof collectionsControllerCreateCollection>>, {data: CollectionCreateDto}> = (props) => {
          const {data} = props ?? {};

          return  collectionsControllerCreateCollection(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CollectionsControllerCreateCollectionMutationResult = NonNullable<Awaited<ReturnType<typeof collectionsControllerCreateCollection>>>
    export type CollectionsControllerCreateCollectionMutationBody = CollectionCreateDto
    export type CollectionsControllerCreateCollectionMutationError = AxiosError<unknown>

    export const useCollectionsControllerCreateCollection = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof collectionsControllerCreateCollection>>, TError,{data: CollectionCreateDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof collectionsControllerCreateCollection>>,
        TError,
        {data: CollectionCreateDto},
        TContext
      > => {

      const mutationOptions = getCollectionsControllerCreateCollectionMutationOptions(options);

      return useMutation(mutationOptions);
    }
    