/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Asteron
 * Novel writing tool
 * OpenAPI spec version: 1.0
 */
import {
  faker
} from '@faker-js/faker'
import {
  HttpResponse,
  delay,
  http
} from 'msw'
import type {
  CollectionGetDto
} from '.././models'

export const getCollectionsControllerGetAllResponseMock = (): CollectionGetDto[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({colour: faker.word.sample(), icon: faker.word.sample(), id: faker.word.sample(), name: faker.word.sample(), parentId: faker.helpers.arrayElement([faker.word.sample(), undefined]), timestamp: `${faker.date.past().toISOString().split('.')[0]}Z`})))

export const getCollectionsControllerGetMyCollectionResponseMock = (): CollectionGetDto[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({colour: faker.word.sample(), icon: faker.word.sample(), id: faker.word.sample(), name: faker.word.sample(), parentId: faker.helpers.arrayElement([faker.word.sample(), undefined]), timestamp: `${faker.date.past().toISOString().split('.')[0]}Z`})))

export const getCollectionsControllerGetCollectionResponseMock = (overrideResponse: Partial< CollectionGetDto > = {}): CollectionGetDto => ({colour: faker.word.sample(), icon: faker.word.sample(), id: faker.word.sample(), name: faker.word.sample(), parentId: faker.helpers.arrayElement([faker.word.sample(), undefined]), timestamp: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse})

export const getCollectionsControllerUpdateCollectionResponseMock = (overrideResponse: Partial< CollectionGetDto > = {}): CollectionGetDto => ({colour: faker.word.sample(), icon: faker.word.sample(), id: faker.word.sample(), name: faker.word.sample(), parentId: faker.helpers.arrayElement([faker.word.sample(), undefined]), timestamp: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse})

export const getCollectionsControllerDeleteCollectionResponseMock = (overrideResponse: Partial< CollectionGetDto > = {}): CollectionGetDto => ({colour: faker.word.sample(), icon: faker.word.sample(), id: faker.word.sample(), name: faker.word.sample(), parentId: faker.helpers.arrayElement([faker.word.sample(), undefined]), timestamp: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse})

export const getCollectionsControllerCreateCollectionResponseMock = (overrideResponse: Partial< CollectionGetDto > = {}): CollectionGetDto => ({colour: faker.word.sample(), icon: faker.word.sample(), id: faker.word.sample(), name: faker.word.sample(), parentId: faker.helpers.arrayElement([faker.word.sample(), undefined]), timestamp: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse})


export const getCollectionsControllerGetAllMockHandler = (overrideResponse?: CollectionGetDto[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<CollectionGetDto[]> | CollectionGetDto[])) => {
  return http.get('*/api/collections', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getCollectionsControllerGetAllResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getCollectionsControllerGetMyCollectionMockHandler = (overrideResponse?: CollectionGetDto[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<CollectionGetDto[]> | CollectionGetDto[])) => {
  return http.get('*/api/collections/mine', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getCollectionsControllerGetMyCollectionResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getCollectionsControllerGetCollectionMockHandler = (overrideResponse?: CollectionGetDto | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<CollectionGetDto> | CollectionGetDto)) => {
  return http.get('*/api/collections/:collectionId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getCollectionsControllerGetCollectionResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getCollectionsControllerUpdateCollectionMockHandler = (overrideResponse?: CollectionGetDto | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<CollectionGetDto> | CollectionGetDto)) => {
  return http.patch('*/api/collections/:collectionId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getCollectionsControllerUpdateCollectionResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getCollectionsControllerDeleteCollectionMockHandler = (overrideResponse?: CollectionGetDto | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<CollectionGetDto> | CollectionGetDto)) => {
  return http.delete('*/api/collections/:collectionId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getCollectionsControllerDeleteCollectionResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getCollectionsControllerCreateCollectionMockHandler = (overrideResponse?: CollectionGetDto | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<CollectionGetDto> | CollectionGetDto)) => {
  return http.post('*/api/collections/create', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getCollectionsControllerCreateCollectionResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}
export const getCollectionsMock = () => [
  getCollectionsControllerGetAllMockHandler(),
  getCollectionsControllerGetMyCollectionMockHandler(),
  getCollectionsControllerGetCollectionMockHandler(),
  getCollectionsControllerUpdateCollectionMockHandler(),
  getCollectionsControllerDeleteCollectionMockHandler(),
  getCollectionsControllerCreateCollectionMockHandler()
]
