/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Asteron
 * Novel writing tool
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  ManuscriptCreateDto,
  ManuscriptGetDto,
  ManuscriptPatchDto
} from '.././models'



/**
 * GET `/manuscript` Get all manuscript
 */
export const manuscriptsControllerGetAll = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ManuscriptGetDto[]>> => {
    
    return axios.default.get(
      `/api/manuscript`,options
    );
  }


export const getManuscriptsControllerGetAllQueryKey = () => {
    return [`/api/manuscript`] as const;
    }

    
export const getManuscriptsControllerGetAllQueryOptions = <TData = Awaited<ReturnType<typeof manuscriptsControllerGetAll>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof manuscriptsControllerGetAll>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getManuscriptsControllerGetAllQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof manuscriptsControllerGetAll>>> = ({ signal }) => manuscriptsControllerGetAll({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof manuscriptsControllerGetAll>>, TError, TData> & { queryKey: QueryKey }
}

export type ManuscriptsControllerGetAllQueryResult = NonNullable<Awaited<ReturnType<typeof manuscriptsControllerGetAll>>>
export type ManuscriptsControllerGetAllQueryError = AxiosError<unknown>


export function useManuscriptsControllerGetAll<TData = Awaited<ReturnType<typeof manuscriptsControllerGetAll>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof manuscriptsControllerGetAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof manuscriptsControllerGetAll>>,
          TError,
          TData
        > , 'initialData'
      >, axios?: AxiosRequestConfig}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useManuscriptsControllerGetAll<TData = Awaited<ReturnType<typeof manuscriptsControllerGetAll>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof manuscriptsControllerGetAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof manuscriptsControllerGetAll>>,
          TError,
          TData
        > , 'initialData'
      >, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useManuscriptsControllerGetAll<TData = Awaited<ReturnType<typeof manuscriptsControllerGetAll>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof manuscriptsControllerGetAll>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }

export function useManuscriptsControllerGetAll<TData = Awaited<ReturnType<typeof manuscriptsControllerGetAll>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof manuscriptsControllerGetAll>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getManuscriptsControllerGetAllQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * GET `/manuscript/mine` Get my manuscript
 */
export const manuscriptsControllerGetMyManuscript = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ManuscriptGetDto[]>> => {
    
    return axios.default.get(
      `/api/manuscript/mine`,options
    );
  }


export const getManuscriptsControllerGetMyManuscriptQueryKey = () => {
    return [`/api/manuscript/mine`] as const;
    }

    
export const getManuscriptsControllerGetMyManuscriptQueryOptions = <TData = Awaited<ReturnType<typeof manuscriptsControllerGetMyManuscript>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof manuscriptsControllerGetMyManuscript>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getManuscriptsControllerGetMyManuscriptQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof manuscriptsControllerGetMyManuscript>>> = ({ signal }) => manuscriptsControllerGetMyManuscript({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof manuscriptsControllerGetMyManuscript>>, TError, TData> & { queryKey: QueryKey }
}

export type ManuscriptsControllerGetMyManuscriptQueryResult = NonNullable<Awaited<ReturnType<typeof manuscriptsControllerGetMyManuscript>>>
export type ManuscriptsControllerGetMyManuscriptQueryError = AxiosError<unknown>


export function useManuscriptsControllerGetMyManuscript<TData = Awaited<ReturnType<typeof manuscriptsControllerGetMyManuscript>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof manuscriptsControllerGetMyManuscript>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof manuscriptsControllerGetMyManuscript>>,
          TError,
          TData
        > , 'initialData'
      >, axios?: AxiosRequestConfig}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useManuscriptsControllerGetMyManuscript<TData = Awaited<ReturnType<typeof manuscriptsControllerGetMyManuscript>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof manuscriptsControllerGetMyManuscript>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof manuscriptsControllerGetMyManuscript>>,
          TError,
          TData
        > , 'initialData'
      >, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useManuscriptsControllerGetMyManuscript<TData = Awaited<ReturnType<typeof manuscriptsControllerGetMyManuscript>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof manuscriptsControllerGetMyManuscript>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }

export function useManuscriptsControllerGetMyManuscript<TData = Awaited<ReturnType<typeof manuscriptsControllerGetMyManuscript>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof manuscriptsControllerGetMyManuscript>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getManuscriptsControllerGetMyManuscriptQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * GET `/manuscript/:collectionId` Get a single collection's information
 */
export const manuscriptsControllerGetManuscript = (
    collectionId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ManuscriptGetDto>> => {
    
    return axios.default.get(
      `/api/manuscript/${collectionId}`,options
    );
  }


export const getManuscriptsControllerGetManuscriptQueryKey = (collectionId: string,) => {
    return [`/api/manuscript/${collectionId}`] as const;
    }

    
export const getManuscriptsControllerGetManuscriptQueryOptions = <TData = Awaited<ReturnType<typeof manuscriptsControllerGetManuscript>>, TError = AxiosError<void>>(collectionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof manuscriptsControllerGetManuscript>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getManuscriptsControllerGetManuscriptQueryKey(collectionId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof manuscriptsControllerGetManuscript>>> = ({ signal }) => manuscriptsControllerGetManuscript(collectionId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(collectionId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof manuscriptsControllerGetManuscript>>, TError, TData> & { queryKey: QueryKey }
}

export type ManuscriptsControllerGetManuscriptQueryResult = NonNullable<Awaited<ReturnType<typeof manuscriptsControllerGetManuscript>>>
export type ManuscriptsControllerGetManuscriptQueryError = AxiosError<void>


export function useManuscriptsControllerGetManuscript<TData = Awaited<ReturnType<typeof manuscriptsControllerGetManuscript>>, TError = AxiosError<void>>(
 collectionId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof manuscriptsControllerGetManuscript>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof manuscriptsControllerGetManuscript>>,
          TError,
          TData
        > , 'initialData'
      >, axios?: AxiosRequestConfig}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useManuscriptsControllerGetManuscript<TData = Awaited<ReturnType<typeof manuscriptsControllerGetManuscript>>, TError = AxiosError<void>>(
 collectionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof manuscriptsControllerGetManuscript>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof manuscriptsControllerGetManuscript>>,
          TError,
          TData
        > , 'initialData'
      >, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useManuscriptsControllerGetManuscript<TData = Awaited<ReturnType<typeof manuscriptsControllerGetManuscript>>, TError = AxiosError<void>>(
 collectionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof manuscriptsControllerGetManuscript>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }

export function useManuscriptsControllerGetManuscript<TData = Awaited<ReturnType<typeof manuscriptsControllerGetManuscript>>, TError = AxiosError<void>>(
 collectionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof manuscriptsControllerGetManuscript>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getManuscriptsControllerGetManuscriptQueryOptions(collectionId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * PATCH `/manuscript/:collectionId` Update a collection (mine or admin only)
 */
export const manuscriptsControllerUpdateManuscript = (
    collectionId: string,
    manuscriptPatchDto: ManuscriptPatchDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ManuscriptGetDto>> => {
    
    return axios.default.patch(
      `/api/manuscript/${collectionId}`,
      manuscriptPatchDto,options
    );
  }



export const getManuscriptsControllerUpdateManuscriptMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof manuscriptsControllerUpdateManuscript>>, TError,{collectionId: string;data: ManuscriptPatchDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof manuscriptsControllerUpdateManuscript>>, TError,{collectionId: string;data: ManuscriptPatchDto}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof manuscriptsControllerUpdateManuscript>>, {collectionId: string;data: ManuscriptPatchDto}> = (props) => {
          const {collectionId,data} = props ?? {};

          return  manuscriptsControllerUpdateManuscript(collectionId,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ManuscriptsControllerUpdateManuscriptMutationResult = NonNullable<Awaited<ReturnType<typeof manuscriptsControllerUpdateManuscript>>>
    export type ManuscriptsControllerUpdateManuscriptMutationBody = ManuscriptPatchDto
    export type ManuscriptsControllerUpdateManuscriptMutationError = AxiosError<unknown>

    export const useManuscriptsControllerUpdateManuscript = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof manuscriptsControllerUpdateManuscript>>, TError,{collectionId: string;data: ManuscriptPatchDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof manuscriptsControllerUpdateManuscript>>,
        TError,
        {collectionId: string;data: ManuscriptPatchDto},
        TContext
      > => {

      const mutationOptions = getManuscriptsControllerUpdateManuscriptMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * DELETE `/manuscript/:collectionId` Delete a collection
 */
export const manuscriptsControllerDeleteManuscript = (
    collectionId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ManuscriptGetDto>> => {
    
    return axios.default.delete(
      `/api/manuscript/${collectionId}`,options
    );
  }



export const getManuscriptsControllerDeleteManuscriptMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof manuscriptsControllerDeleteManuscript>>, TError,{collectionId: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof manuscriptsControllerDeleteManuscript>>, TError,{collectionId: string}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof manuscriptsControllerDeleteManuscript>>, {collectionId: string}> = (props) => {
          const {collectionId} = props ?? {};

          return  manuscriptsControllerDeleteManuscript(collectionId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ManuscriptsControllerDeleteManuscriptMutationResult = NonNullable<Awaited<ReturnType<typeof manuscriptsControllerDeleteManuscript>>>
    
    export type ManuscriptsControllerDeleteManuscriptMutationError = AxiosError<unknown>

    export const useManuscriptsControllerDeleteManuscript = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof manuscriptsControllerDeleteManuscript>>, TError,{collectionId: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof manuscriptsControllerDeleteManuscript>>,
        TError,
        {collectionId: string},
        TContext
      > => {

      const mutationOptions = getManuscriptsControllerDeleteManuscriptMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * POST `/manuscript/create`
Create a collection in our backend, (NOT) in the Firebase
Please be careful with this API call
(though the Firebase collection creation happends automatically when they first log in)
 */
export const manuscriptsControllerCreateManuscript = (
    manuscriptCreateDto: ManuscriptCreateDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ManuscriptGetDto>> => {
    
    return axios.default.post(
      `/api/manuscript/create`,
      manuscriptCreateDto,options
    );
  }



export const getManuscriptsControllerCreateManuscriptMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof manuscriptsControllerCreateManuscript>>, TError,{data: ManuscriptCreateDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof manuscriptsControllerCreateManuscript>>, TError,{data: ManuscriptCreateDto}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof manuscriptsControllerCreateManuscript>>, {data: ManuscriptCreateDto}> = (props) => {
          const {data} = props ?? {};

          return  manuscriptsControllerCreateManuscript(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ManuscriptsControllerCreateManuscriptMutationResult = NonNullable<Awaited<ReturnType<typeof manuscriptsControllerCreateManuscript>>>
    export type ManuscriptsControllerCreateManuscriptMutationBody = ManuscriptCreateDto
    export type ManuscriptsControllerCreateManuscriptMutationError = AxiosError<unknown>

    export const useManuscriptsControllerCreateManuscript = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof manuscriptsControllerCreateManuscript>>, TError,{data: ManuscriptCreateDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof manuscriptsControllerCreateManuscript>>,
        TError,
        {data: ManuscriptCreateDto},
        TContext
      > => {

      const mutationOptions = getManuscriptsControllerCreateManuscriptMutationOptions(options);

      return useMutation(mutationOptions);
    }
    