/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Asteron
 * Novel writing tool
 * OpenAPI spec version: 1.0
 */
import {
  faker
} from '@faker-js/faker'
import {
  HttpResponse,
  delay,
  http
} from 'msw'
import type {
  ManuscriptGetDto
} from '.././models'

export const getManuscriptsControllerGetAllResponseMock = (): ManuscriptGetDto[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({collections: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.word.sample())), colour: faker.helpers.arrayElement([faker.word.sample(), undefined]), icon: faker.helpers.arrayElement([faker.word.sample(), undefined]), id: faker.word.sample(), image: faker.helpers.arrayElement([faker.word.sample(), undefined]), name: faker.word.sample(), timestamp: `${faker.date.past().toISOString().split('.')[0]}Z`})))

export const getManuscriptsControllerGetMyManuscriptResponseMock = (): ManuscriptGetDto[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({collections: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.word.sample())), colour: faker.helpers.arrayElement([faker.word.sample(), undefined]), icon: faker.helpers.arrayElement([faker.word.sample(), undefined]), id: faker.word.sample(), image: faker.helpers.arrayElement([faker.word.sample(), undefined]), name: faker.word.sample(), timestamp: `${faker.date.past().toISOString().split('.')[0]}Z`})))

export const getManuscriptsControllerGetManuscriptResponseMock = (overrideResponse: Partial< ManuscriptGetDto > = {}): ManuscriptGetDto => ({collections: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.word.sample())), colour: faker.helpers.arrayElement([faker.word.sample(), undefined]), icon: faker.helpers.arrayElement([faker.word.sample(), undefined]), id: faker.word.sample(), image: faker.helpers.arrayElement([faker.word.sample(), undefined]), name: faker.word.sample(), timestamp: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse})

export const getManuscriptsControllerUpdateManuscriptResponseMock = (overrideResponse: Partial< ManuscriptGetDto > = {}): ManuscriptGetDto => ({collections: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.word.sample())), colour: faker.helpers.arrayElement([faker.word.sample(), undefined]), icon: faker.helpers.arrayElement([faker.word.sample(), undefined]), id: faker.word.sample(), image: faker.helpers.arrayElement([faker.word.sample(), undefined]), name: faker.word.sample(), timestamp: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse})

export const getManuscriptsControllerDeleteManuscriptResponseMock = (overrideResponse: Partial< ManuscriptGetDto > = {}): ManuscriptGetDto => ({collections: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.word.sample())), colour: faker.helpers.arrayElement([faker.word.sample(), undefined]), icon: faker.helpers.arrayElement([faker.word.sample(), undefined]), id: faker.word.sample(), image: faker.helpers.arrayElement([faker.word.sample(), undefined]), name: faker.word.sample(), timestamp: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse})

export const getManuscriptsControllerCreateManuscriptResponseMock = (overrideResponse: Partial< ManuscriptGetDto > = {}): ManuscriptGetDto => ({collections: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.word.sample())), colour: faker.helpers.arrayElement([faker.word.sample(), undefined]), icon: faker.helpers.arrayElement([faker.word.sample(), undefined]), id: faker.word.sample(), image: faker.helpers.arrayElement([faker.word.sample(), undefined]), name: faker.word.sample(), timestamp: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse})


export const getManuscriptsControllerGetAllMockHandler = (overrideResponse?: ManuscriptGetDto[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ManuscriptGetDto[]> | ManuscriptGetDto[])) => {
  return http.get('*/api/manuscript', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getManuscriptsControllerGetAllResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getManuscriptsControllerGetMyManuscriptMockHandler = (overrideResponse?: ManuscriptGetDto[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ManuscriptGetDto[]> | ManuscriptGetDto[])) => {
  return http.get('*/api/manuscript/mine', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getManuscriptsControllerGetMyManuscriptResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getManuscriptsControllerGetManuscriptMockHandler = (overrideResponse?: ManuscriptGetDto | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ManuscriptGetDto> | ManuscriptGetDto)) => {
  return http.get('*/api/manuscript/:collectionId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getManuscriptsControllerGetManuscriptResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getManuscriptsControllerUpdateManuscriptMockHandler = (overrideResponse?: ManuscriptGetDto | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<ManuscriptGetDto> | ManuscriptGetDto)) => {
  return http.patch('*/api/manuscript/:collectionId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getManuscriptsControllerUpdateManuscriptResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getManuscriptsControllerDeleteManuscriptMockHandler = (overrideResponse?: ManuscriptGetDto | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<ManuscriptGetDto> | ManuscriptGetDto)) => {
  return http.delete('*/api/manuscript/:collectionId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getManuscriptsControllerDeleteManuscriptResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getManuscriptsControllerCreateManuscriptMockHandler = (overrideResponse?: ManuscriptGetDto | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ManuscriptGetDto> | ManuscriptGetDto)) => {
  return http.post('*/api/manuscript/create', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getManuscriptsControllerCreateManuscriptResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}
export const getManuscriptsMock = () => [
  getManuscriptsControllerGetAllMockHandler(),
  getManuscriptsControllerGetMyManuscriptMockHandler(),
  getManuscriptsControllerGetManuscriptMockHandler(),
  getManuscriptsControllerUpdateManuscriptMockHandler(),
  getManuscriptsControllerDeleteManuscriptMockHandler(),
  getManuscriptsControllerCreateManuscriptMockHandler()
]
