/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Second Stack
 * The cool new boilerplate
 * OpenAPI spec version: 2.0
 */
import {
  faker
} from '@faker-js/faker'
import {
  HttpResponse,
  delay,
  http
} from 'msw'

export const getPingControllerPingResponseMock = (): string => (faker.word.sample())

export const getPingControllerProtectedResponseMock = (): string => (faker.word.sample())


export const getPingControllerPingMockHandler = (overrideResponse?: string | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<string> | string)) => {
  return http.get('*/api/ping', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getPingControllerPingResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getPingControllerProtectedMockHandler = (overrideResponse?: string | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<string> | string)) => {
  return http.get('*/api/ping/protected', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getPingControllerProtectedResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}
export const getPingMock = () => [
  getPingControllerPingMockHandler(),
  getPingControllerProtectedMockHandler()
]
