/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Asteron
 * Novel writing tool
 * OpenAPI spec version: 1.0
 */

export interface CategoryGetDto {
  colour: string;
  icon: string;
  id: string;
  name: string;
}
