/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Asteron
 * Novel writing tool
 * OpenAPI spec version: 1.0
 */

export interface CollectionGetDto {
  colour: string;
  icon: string;
  id: string;
  name: string;
  parentId?: string;
  timestamp: string;
}
