/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Asteron
 * Novel writing tool
 * OpenAPI spec version: 1.0
 */
import type { ElementGetDtoNamesItem } from './elementGetDtoNamesItem';

export interface ElementGetDto {
  collections: string[];
  colour: string;
  defaultName: string;
  id: string;
  image: string;
  names: ElementGetDtoNamesItem[];
  timestamp: string;
}
