/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Asteron
 * Novel writing tool
 * OpenAPI spec version: 1.0
 */

export interface ManuscriptGetDto {
  collections: string[];
  colour?: string;
  icon?: string;
  id: string;
  image?: string;
  name: string;
  timestamp: string;
}
