/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Second Stack
 * The cool new boilerplate
 * OpenAPI spec version: 2.0
 */
import type { UserAuthGetDtoFirebaseData } from './userAuthGetDtoFirebaseData';
import type { UserAuthGetDtoProvidersItem } from './userAuthGetDtoProvidersItem';
import type { UserAuthGetDtoRolesItem } from './userAuthGetDtoRolesItem';

export interface UserAuthGetDto {
  deleted: boolean;
  email: string;
  familyName?: string;
  firebaseData: UserAuthGetDtoFirebaseData;
  firebaseId?: string;
  givenName?: string;
  id: string;
  locked: boolean;
  phone?: string;
  providers?: UserAuthGetDtoProvidersItem[];
  /** User roles
@enum roles type of UserRole */
  roles: UserAuthGetDtoRolesItem[];
  timestamp: string;
}
