/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Asteron
 * Novel writing tool
 * OpenAPI spec version: 1.0
 */
import type { UsersControllerAddUserRoleRole } from './usersControllerAddUserRoleRole';

export type UsersControllerAddUserRoleParams = {
userId: string;
role: UsersControllerAddUserRoleRole;
};
