/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Second Stack
 * The cool new boilerplate
 * OpenAPI spec version: 2.0
 */

export type UsersControllerRmUserRoleRole = typeof UsersControllerRmUserRoleRole[keyof typeof UsersControllerRmUserRoleRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UsersControllerRmUserRoleRole = {
  Admin: 'Admin',
  User: 'User',
} as const;
