/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Asteron
 * Novel writing tool
 * OpenAPI spec version: 1.0
 */
import type { UserGetDtoRolesItem } from './userGetDtoRolesItem';

export interface UserGetDto {
  credit?: number;
  creditDescription?: string;
  deleted: boolean;
  email: string;
  emailVerified?: boolean;
  familyName?: string;
  givenName?: string;
  id: string;
  locked: boolean;
  phone?: string;
  /** User roles
@enum roles type of UserRole */
  roles: UserGetDtoRolesItem[];
  teamLimit?: number;
  timestamp: string;
}
