/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Asteron
 * Novel writing tool
 * OpenAPI spec version: 1.0
 */
import type { UserCreateDtoFirebaseData } from './userCreateDtoFirebaseData';
import type { UserCreateDtoProvidersItem } from './userCreateDtoProvidersItem';
import type { UserCreateDtoRolesItem } from './userCreateDtoRolesItem';

export interface UserCreateDto {
  email: string;
  emailVerified?: boolean;
  familyName?: string;
  firebaseData: UserCreateDtoFirebaseData;
  firebaseId?: string;
  givenName?: string;
  phone?: string;
  picture?: string;
  providers?: UserCreateDtoProvidersItem[];
  roles: UserCreateDtoRolesItem[];
}
