/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Second Stack
 * The cool new boilerplate
 * OpenAPI spec version: 2.0
 */
import type { UsersControllerAddUserRoleRole } from './usersControllerAddUserRoleRole';

export type UsersControllerAddUserRoleParams = {
userId: string;
role: UsersControllerAddUserRoleRole;
};
