/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Asteron
 * Novel writing tool
 * OpenAPI spec version: 1.0
 */

export type UsersControllerAddUserRoleRole = typeof UsersControllerAddUserRoleRole[keyof typeof UsersControllerAddUserRoleRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UsersControllerAddUserRoleRole = {
  Admin: 'Admin',
  User: 'User',
} as const;
