/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Asteron
 * Novel writing tool
 * OpenAPI spec version: 1.0
 */

export interface UserPublicGetDto {
  avatar?: string;
  deleted: boolean;
  email: string;
  familyName?: string;
  givenName?: string;
  id: string;
  locked: boolean;
}
