/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Second Stack
 * The cool new boilerplate
 * OpenAPI spec version: 2.0
 */
import type { UserPopulatedGetDtoRolesItem } from './userPopulatedGetDtoRolesItem';

export interface UserPopulatedGetDto {
  deleted: boolean;
  email: string;
  familyName?: string;
  givenName?: string;
  id: string;
  locked: boolean;
  phone: string;
  /** User roles */
  roles: UserPopulatedGetDtoRolesItem[];
  teamLimit?: number;
  timestamp: string;
}
