/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Second Stack
 * The cool new boilerplate
 * OpenAPI spec version: 2.0
 */

export interface UserPublicGetDto {
  avatar?: string;
  deleted: boolean;
  email: string;
  familyName?: string;
  givenName?: string;
  id: string;
  locked: boolean;
}
