/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Asteron
 * Novel writing tool
 * OpenAPI spec version: 1.0
 */
import {
  faker
} from '@faker-js/faker'
import {
  HttpResponse,
  delay,
  http
} from 'msw'
import type {
  GraphGetDto,
  UserAuthGetDto,
  UserCheckEmailDto,
  UserGetDto,
  UserPopulatedGetDto,
  UserPublicGetDto,
  UserStatsGetDto
} from '.././models'

export const getUsersControllerGetAllResponseMock = (): UserPublicGetDto[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({avatar: faker.helpers.arrayElement([faker.word.sample(), undefined]), deleted: faker.datatype.boolean(), email: faker.word.sample(), familyName: faker.helpers.arrayElement([faker.word.sample(), undefined]), givenName: faker.helpers.arrayElement([faker.word.sample(), undefined]), id: faker.word.sample(), locked: faker.datatype.boolean()})))

export const getUsersControllerGetAllDeletedResponseMock = (): UserGetDto[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({credit: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), creditDescription: faker.helpers.arrayElement([faker.word.sample(), undefined]), deleted: faker.datatype.boolean(), email: faker.word.sample(), emailVerified: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), familyName: faker.helpers.arrayElement([faker.word.sample(), undefined]), givenName: faker.helpers.arrayElement([faker.word.sample(), undefined]), id: faker.word.sample(), locked: faker.datatype.boolean(), phone: faker.helpers.arrayElement([faker.word.sample(), undefined]), roles: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({})), teamLimit: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), timestamp: `${faker.date.past().toISOString().split('.')[0]}Z`})))

export const getUsersControllerGetMeResponseMock = (overrideResponse: Partial< UserAuthGetDto > = {}): UserAuthGetDto => ({deleted: faker.datatype.boolean(), email: faker.word.sample(), familyName: faker.helpers.arrayElement([faker.word.sample(), undefined]), firebaseData: {emailVerified: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), picture: faker.helpers.arrayElement([faker.word.sample(), undefined])}, firebaseId: faker.helpers.arrayElement([faker.word.sample(), undefined]), givenName: faker.helpers.arrayElement([faker.word.sample(), undefined]), id: faker.word.sample(), locked: faker.datatype.boolean(), phone: faker.helpers.arrayElement([faker.word.sample(), undefined]), providers: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({})), undefined]), roles: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({})), timestamp: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse})

export const getUsersControllerGetUserResponseMock = (overrideResponse: Partial< UserPopulatedGetDto > = {}): UserPopulatedGetDto => ({deleted: faker.datatype.boolean(), email: faker.word.sample(), familyName: faker.helpers.arrayElement([faker.word.sample(), undefined]), givenName: faker.helpers.arrayElement([faker.word.sample(), undefined]), id: faker.word.sample(), locked: faker.datatype.boolean(), phone: faker.word.sample(), roles: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({})), teamLimit: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), timestamp: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse})

export const getUsersControllerUpdateUserResponseMock = (overrideResponse: Partial< UserAuthGetDto > = {}): UserAuthGetDto => ({deleted: faker.datatype.boolean(), email: faker.word.sample(), familyName: faker.helpers.arrayElement([faker.word.sample(), undefined]), firebaseData: {emailVerified: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), picture: faker.helpers.arrayElement([faker.word.sample(), undefined])}, firebaseId: faker.helpers.arrayElement([faker.word.sample(), undefined]), givenName: faker.helpers.arrayElement([faker.word.sample(), undefined]), id: faker.word.sample(), locked: faker.datatype.boolean(), phone: faker.helpers.arrayElement([faker.word.sample(), undefined]), providers: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({})), undefined]), roles: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({})), timestamp: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse})

export const getUsersControllerGetUserPublicResponseMock = (overrideResponse: Partial< UserPublicGetDto > = {}): UserPublicGetDto => ({avatar: faker.helpers.arrayElement([faker.word.sample(), undefined]), deleted: faker.datatype.boolean(), email: faker.word.sample(), familyName: faker.helpers.arrayElement([faker.word.sample(), undefined]), givenName: faker.helpers.arrayElement([faker.word.sample(), undefined]), id: faker.word.sample(), locked: faker.datatype.boolean(), ...overrideResponse})

export const getUsersControllerUpdateUserVisibilityResponseMock = (overrideResponse: Partial< UserAuthGetDto > = {}): UserAuthGetDto => ({deleted: faker.datatype.boolean(), email: faker.word.sample(), familyName: faker.helpers.arrayElement([faker.word.sample(), undefined]), firebaseData: {emailVerified: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), picture: faker.helpers.arrayElement([faker.word.sample(), undefined])}, firebaseId: faker.helpers.arrayElement([faker.word.sample(), undefined]), givenName: faker.helpers.arrayElement([faker.word.sample(), undefined]), id: faker.word.sample(), locked: faker.datatype.boolean(), phone: faker.helpers.arrayElement([faker.word.sample(), undefined]), providers: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({})), undefined]), roles: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({})), timestamp: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse})

export const getUsersControllerCheckEmailResponseMock = (overrideResponse: Partial< UserCheckEmailDto > = {}): UserCheckEmailDto => ({email: faker.word.sample(), id: faker.helpers.arrayElement([faker.word.sample(), null]), providers: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.word.sample())), ...overrideResponse})

export const getUsersControllerAddUserRoleResponseMock = (overrideResponse: Partial< UserGetDto | UserAuthGetDto > = {}): UserGetDto | UserAuthGetDto => (faker.helpers.arrayElement([{credit: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), creditDescription: faker.helpers.arrayElement([faker.word.sample(), undefined]), deleted: faker.datatype.boolean(), email: faker.word.sample(), emailVerified: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), familyName: faker.helpers.arrayElement([faker.word.sample(), undefined]), givenName: faker.helpers.arrayElement([faker.word.sample(), undefined]), id: faker.word.sample(), locked: faker.datatype.boolean(), phone: faker.helpers.arrayElement([faker.word.sample(), undefined]), roles: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({})), teamLimit: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), timestamp: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse}, {deleted: faker.datatype.boolean(), email: faker.word.sample(), familyName: faker.helpers.arrayElement([faker.word.sample(), undefined]), firebaseData: {emailVerified: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), picture: faker.helpers.arrayElement([faker.word.sample(), undefined])}, firebaseId: faker.helpers.arrayElement([faker.word.sample(), undefined]), givenName: faker.helpers.arrayElement([faker.word.sample(), undefined]), id: faker.word.sample(), locked: faker.datatype.boolean(), phone: faker.helpers.arrayElement([faker.word.sample(), undefined]), providers: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({})), undefined]), roles: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({})), timestamp: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse}]))

export const getUsersControllerRmUserRoleResponseMock = (overrideResponse: Partial< UserGetDto > = {}): UserGetDto => ({credit: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), creditDescription: faker.helpers.arrayElement([faker.word.sample(), undefined]), deleted: faker.datatype.boolean(), email: faker.word.sample(), emailVerified: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), familyName: faker.helpers.arrayElement([faker.word.sample(), undefined]), givenName: faker.helpers.arrayElement([faker.word.sample(), undefined]), id: faker.word.sample(), locked: faker.datatype.boolean(), phone: faker.helpers.arrayElement([faker.word.sample(), undefined]), roles: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({})), teamLimit: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), timestamp: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse})

export const getUsersControllerUploadUserAvatarResponseMock = (overrideResponse: Partial< UserPublicGetDto | UserGetDto > = {}): UserPublicGetDto | UserGetDto => (faker.helpers.arrayElement([{avatar: faker.helpers.arrayElement([faker.word.sample(), undefined]), deleted: faker.datatype.boolean(), email: faker.word.sample(), familyName: faker.helpers.arrayElement([faker.word.sample(), undefined]), givenName: faker.helpers.arrayElement([faker.word.sample(), undefined]), id: faker.word.sample(), locked: faker.datatype.boolean(), ...overrideResponse}, {credit: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), creditDescription: faker.helpers.arrayElement([faker.word.sample(), undefined]), deleted: faker.datatype.boolean(), email: faker.word.sample(), emailVerified: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), familyName: faker.helpers.arrayElement([faker.word.sample(), undefined]), givenName: faker.helpers.arrayElement([faker.word.sample(), undefined]), id: faker.word.sample(), locked: faker.datatype.boolean(), phone: faker.helpers.arrayElement([faker.word.sample(), undefined]), roles: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({})), teamLimit: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), timestamp: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse}]))

export const getUsersControllerGetStatsByProgramResponseMock = (overrideResponse: Partial< UserStatsGetDto > = {}): UserStatsGetDto => ({numberOfUsers: faker.number.int({min: undefined, max: undefined}), ...overrideResponse})

export const getUsersControllerGetGraphResponseMock = (): GraphGetDto[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({day: `${faker.date.past().toISOString().split('.')[0]}Z`, value: faker.number.int({min: undefined, max: undefined})})))

export const getUsersControllerCreateUserResponseMock = (overrideResponse: Partial< UserGetDto > = {}): UserGetDto => ({credit: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), creditDescription: faker.helpers.arrayElement([faker.word.sample(), undefined]), deleted: faker.datatype.boolean(), email: faker.word.sample(), emailVerified: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), familyName: faker.helpers.arrayElement([faker.word.sample(), undefined]), givenName: faker.helpers.arrayElement([faker.word.sample(), undefined]), id: faker.word.sample(), locked: faker.datatype.boolean(), phone: faker.helpers.arrayElement([faker.word.sample(), undefined]), roles: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({})), teamLimit: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), timestamp: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse})


export const getUsersControllerGetAllMockHandler = (overrideResponse?: UserPublicGetDto[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<UserPublicGetDto[]> | UserPublicGetDto[])) => {
  return http.get('*/api/users', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getUsersControllerGetAllResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getUsersControllerGetAllDeletedMockHandler = (overrideResponse?: UserGetDto[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<UserGetDto[]> | UserGetDto[])) => {
  return http.get('*/api/users/deleted', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getUsersControllerGetAllDeletedResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getUsersControllerGetMeMockHandler = (overrideResponse?: UserAuthGetDto | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<UserAuthGetDto> | UserAuthGetDto)) => {
  return http.get('*/api/users/me', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getUsersControllerGetMeResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getUsersControllerGetUserMockHandler = (overrideResponse?: UserPopulatedGetDto | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<UserPopulatedGetDto> | UserPopulatedGetDto)) => {
  return http.get('*/api/users/:userId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getUsersControllerGetUserResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getUsersControllerUpdateUserMockHandler = (overrideResponse?: UserAuthGetDto | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<UserAuthGetDto> | UserAuthGetDto)) => {
  return http.patch('*/api/users/:userId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getUsersControllerUpdateUserResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getUsersControllerGetUserPublicMockHandler = (overrideResponse?: UserPublicGetDto | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<UserPublicGetDto> | UserPublicGetDto)) => {
  return http.get('*/api/users/:userId/public', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getUsersControllerGetUserPublicResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getUsersControllerUpdateUserVisibilityMockHandler = (overrideResponse?: UserAuthGetDto | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<UserAuthGetDto> | UserAuthGetDto)) => {
  return http.patch('*/api/users/:userId/visibility', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getUsersControllerUpdateUserVisibilityResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getUsersControllerCheckEmailMockHandler = (overrideResponse?: UserCheckEmailDto | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<UserCheckEmailDto> | UserCheckEmailDto)) => {
  return http.get('*/api/users/email/:email', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getUsersControllerCheckEmailResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getUsersControllerAddUserRoleMockHandler = (overrideResponse?: UserGetDto | UserAuthGetDto | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<UserGetDto | UserAuthGetDto> | UserGetDto | UserAuthGetDto)) => {
  return http.post('*/api/users/:userId/role/:role', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getUsersControllerAddUserRoleResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getUsersControllerRmUserRoleMockHandler = (overrideResponse?: UserGetDto | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<UserGetDto> | UserGetDto)) => {
  return http.delete('*/api/users/:userId/role/:role', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getUsersControllerRmUserRoleResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getUsersControllerUploadUserAvatarMockHandler = (overrideResponse?: UserPublicGetDto | UserGetDto | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<UserPublicGetDto | UserGetDto> | UserPublicGetDto | UserGetDto)) => {
  return http.post('*/api/users/:userId/avatar', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getUsersControllerUploadUserAvatarResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getUsersControllerGetStatsByProgramMockHandler = (overrideResponse?: UserStatsGetDto | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<UserStatsGetDto> | UserStatsGetDto)) => {
  return http.get('*/api/users/stats/metrics', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getUsersControllerGetStatsByProgramResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getUsersControllerGetGraphMockHandler = (overrideResponse?: GraphGetDto[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GraphGetDto[]> | GraphGetDto[])) => {
  return http.get('*/api/users/stats/graph', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getUsersControllerGetGraphResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getUsersControllerCreateUserMockHandler = (overrideResponse?: UserGetDto | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<UserGetDto> | UserGetDto)) => {
  return http.post('*/api/users/create', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getUsersControllerCreateUserResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}
export const getUsersMock = () => [
  getUsersControllerGetAllMockHandler(),
  getUsersControllerGetAllDeletedMockHandler(),
  getUsersControllerGetMeMockHandler(),
  getUsersControllerGetUserMockHandler(),
  getUsersControllerUpdateUserMockHandler(),
  getUsersControllerGetUserPublicMockHandler(),
  getUsersControllerUpdateUserVisibilityMockHandler(),
  getUsersControllerCheckEmailMockHandler(),
  getUsersControllerAddUserRoleMockHandler(),
  getUsersControllerRmUserRoleMockHandler(),
  getUsersControllerUploadUserAvatarMockHandler(),
  getUsersControllerGetStatsByProgramMockHandler(),
  getUsersControllerGetGraphMockHandler(),
  getUsersControllerCreateUserMockHandler()
]
