/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Asteron
 * Novel writing tool
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  GraphGetDto,
  UserAuthGetDto,
  UserCheckEmailDto,
  UserCreateDto,
  UserGetDto,
  UserPatchDto,
  UserPatchVisibilityDto,
  UserPopulatedGetDto,
  UserPublicGetDto,
  UserStatsGetDto,
  UsersControllerAddUserRoleParams,
  UsersControllerRmUserRoleParams,
  UsersControllerUploadUserAvatarBody
} from '.././models'



/**
 * GET `/users` Get all users
 */
export const usersControllerGetAll = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserPublicGetDto[]>> => {
    
    return axios.default.get(
      `/api/users`,options
    );
  }


export const getUsersControllerGetAllQueryKey = () => {
    return [`/api/users`] as const;
    }

    
export const getUsersControllerGetAllQueryOptions = <TData = Awaited<ReturnType<typeof usersControllerGetAll>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetAll>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersControllerGetAllQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersControllerGetAll>>> = ({ signal }) => usersControllerGetAll({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetAll>>, TError, TData> & { queryKey: QueryKey }
}

export type UsersControllerGetAllQueryResult = NonNullable<Awaited<ReturnType<typeof usersControllerGetAll>>>
export type UsersControllerGetAllQueryError = AxiosError<unknown>


export function useUsersControllerGetAll<TData = Awaited<ReturnType<typeof usersControllerGetAll>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetAll>>,
          TError,
          TData
        > , 'initialData'
      >, axios?: AxiosRequestConfig}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useUsersControllerGetAll<TData = Awaited<ReturnType<typeof usersControllerGetAll>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetAll>>,
          TError,
          TData
        > , 'initialData'
      >, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useUsersControllerGetAll<TData = Awaited<ReturnType<typeof usersControllerGetAll>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetAll>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }

export function useUsersControllerGetAll<TData = Awaited<ReturnType<typeof usersControllerGetAll>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetAll>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getUsersControllerGetAllQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * GET `/users/deleted` Get all deleted users
 */
export const usersControllerGetAllDeleted = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserGetDto[]>> => {
    
    return axios.default.get(
      `/api/users/deleted`,options
    );
  }


export const getUsersControllerGetAllDeletedQueryKey = () => {
    return [`/api/users/deleted`] as const;
    }

    
export const getUsersControllerGetAllDeletedQueryOptions = <TData = Awaited<ReturnType<typeof usersControllerGetAllDeleted>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetAllDeleted>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersControllerGetAllDeletedQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersControllerGetAllDeleted>>> = ({ signal }) => usersControllerGetAllDeleted({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetAllDeleted>>, TError, TData> & { queryKey: QueryKey }
}

export type UsersControllerGetAllDeletedQueryResult = NonNullable<Awaited<ReturnType<typeof usersControllerGetAllDeleted>>>
export type UsersControllerGetAllDeletedQueryError = AxiosError<unknown>


export function useUsersControllerGetAllDeleted<TData = Awaited<ReturnType<typeof usersControllerGetAllDeleted>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetAllDeleted>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetAllDeleted>>,
          TError,
          TData
        > , 'initialData'
      >, axios?: AxiosRequestConfig}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useUsersControllerGetAllDeleted<TData = Awaited<ReturnType<typeof usersControllerGetAllDeleted>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetAllDeleted>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetAllDeleted>>,
          TError,
          TData
        > , 'initialData'
      >, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useUsersControllerGetAllDeleted<TData = Awaited<ReturnType<typeof usersControllerGetAllDeleted>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetAllDeleted>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }

export function useUsersControllerGetAllDeleted<TData = Awaited<ReturnType<typeof usersControllerGetAllDeleted>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetAllDeleted>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getUsersControllerGetAllDeletedQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * GET `/users/me` Get my user information
 */
export const usersControllerGetMe = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserAuthGetDto>> => {
    
    return axios.default.get(
      `/api/users/me`,options
    );
  }


export const getUsersControllerGetMeQueryKey = () => {
    return [`/api/users/me`] as const;
    }

    
export const getUsersControllerGetMeQueryOptions = <TData = Awaited<ReturnType<typeof usersControllerGetMe>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetMe>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersControllerGetMeQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersControllerGetMe>>> = ({ signal }) => usersControllerGetMe({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetMe>>, TError, TData> & { queryKey: QueryKey }
}

export type UsersControllerGetMeQueryResult = NonNullable<Awaited<ReturnType<typeof usersControllerGetMe>>>
export type UsersControllerGetMeQueryError = AxiosError<unknown>


export function useUsersControllerGetMe<TData = Awaited<ReturnType<typeof usersControllerGetMe>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetMe>>,
          TError,
          TData
        > , 'initialData'
      >, axios?: AxiosRequestConfig}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useUsersControllerGetMe<TData = Awaited<ReturnType<typeof usersControllerGetMe>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetMe>>,
          TError,
          TData
        > , 'initialData'
      >, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useUsersControllerGetMe<TData = Awaited<ReturnType<typeof usersControllerGetMe>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetMe>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }

export function useUsersControllerGetMe<TData = Awaited<ReturnType<typeof usersControllerGetMe>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetMe>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getUsersControllerGetMeQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * GET `/users/:userId` Get a single user's information
 */
export const usersControllerGetUser = (
    userId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserPopulatedGetDto>> => {
    
    return axios.default.get(
      `/api/users/${userId}`,options
    );
  }


export const getUsersControllerGetUserQueryKey = (userId: string,) => {
    return [`/api/users/${userId}`] as const;
    }

    
export const getUsersControllerGetUserQueryOptions = <TData = Awaited<ReturnType<typeof usersControllerGetUser>>, TError = AxiosError<void>>(userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUser>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersControllerGetUserQueryKey(userId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersControllerGetUser>>> = ({ signal }) => usersControllerGetUser(userId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(userId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUser>>, TError, TData> & { queryKey: QueryKey }
}

export type UsersControllerGetUserQueryResult = NonNullable<Awaited<ReturnType<typeof usersControllerGetUser>>>
export type UsersControllerGetUserQueryError = AxiosError<void>


export function useUsersControllerGetUser<TData = Awaited<ReturnType<typeof usersControllerGetUser>>, TError = AxiosError<void>>(
 userId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUser>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetUser>>,
          TError,
          TData
        > , 'initialData'
      >, axios?: AxiosRequestConfig}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useUsersControllerGetUser<TData = Awaited<ReturnType<typeof usersControllerGetUser>>, TError = AxiosError<void>>(
 userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUser>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetUser>>,
          TError,
          TData
        > , 'initialData'
      >, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useUsersControllerGetUser<TData = Awaited<ReturnType<typeof usersControllerGetUser>>, TError = AxiosError<void>>(
 userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUser>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }

export function useUsersControllerGetUser<TData = Awaited<ReturnType<typeof usersControllerGetUser>>, TError = AxiosError<void>>(
 userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUser>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getUsersControllerGetUserQueryOptions(userId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * PATCH `/users/:userId` Update a user (me or admin only)
 */
export const usersControllerUpdateUser = (
    userId: string,
    userPatchDto: UserPatchDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserAuthGetDto>> => {
    
    return axios.default.patch(
      `/api/users/${userId}`,
      userPatchDto,options
    );
  }



export const getUsersControllerUpdateUserMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerUpdateUser>>, TError,{userId: string;data: UserPatchDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof usersControllerUpdateUser>>, TError,{userId: string;data: UserPatchDto}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof usersControllerUpdateUser>>, {userId: string;data: UserPatchDto}> = (props) => {
          const {userId,data} = props ?? {};

          return  usersControllerUpdateUser(userId,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UsersControllerUpdateUserMutationResult = NonNullable<Awaited<ReturnType<typeof usersControllerUpdateUser>>>
    export type UsersControllerUpdateUserMutationBody = UserPatchDto
    export type UsersControllerUpdateUserMutationError = AxiosError<unknown>

    export const useUsersControllerUpdateUser = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerUpdateUser>>, TError,{userId: string;data: UserPatchDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof usersControllerUpdateUser>>,
        TError,
        {userId: string;data: UserPatchDto},
        TContext
      > => {

      const mutationOptions = getUsersControllerUpdateUserMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * GET `/users/:userId/public` Get a single user's PUBLIC information
 */
export const usersControllerGetUserPublic = (
    userId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserPublicGetDto>> => {
    
    return axios.default.get(
      `/api/users/${userId}/public`,options
    );
  }


export const getUsersControllerGetUserPublicQueryKey = (userId: string,) => {
    return [`/api/users/${userId}/public`] as const;
    }

    
export const getUsersControllerGetUserPublicQueryOptions = <TData = Awaited<ReturnType<typeof usersControllerGetUserPublic>>, TError = AxiosError<unknown>>(userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUserPublic>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersControllerGetUserPublicQueryKey(userId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersControllerGetUserPublic>>> = ({ signal }) => usersControllerGetUserPublic(userId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(userId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUserPublic>>, TError, TData> & { queryKey: QueryKey }
}

export type UsersControllerGetUserPublicQueryResult = NonNullable<Awaited<ReturnType<typeof usersControllerGetUserPublic>>>
export type UsersControllerGetUserPublicQueryError = AxiosError<unknown>


export function useUsersControllerGetUserPublic<TData = Awaited<ReturnType<typeof usersControllerGetUserPublic>>, TError = AxiosError<unknown>>(
 userId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUserPublic>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetUserPublic>>,
          TError,
          TData
        > , 'initialData'
      >, axios?: AxiosRequestConfig}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useUsersControllerGetUserPublic<TData = Awaited<ReturnType<typeof usersControllerGetUserPublic>>, TError = AxiosError<unknown>>(
 userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUserPublic>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetUserPublic>>,
          TError,
          TData
        > , 'initialData'
      >, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useUsersControllerGetUserPublic<TData = Awaited<ReturnType<typeof usersControllerGetUserPublic>>, TError = AxiosError<unknown>>(
 userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUserPublic>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }

export function useUsersControllerGetUserPublic<TData = Awaited<ReturnType<typeof usersControllerGetUserPublic>>, TError = AxiosError<unknown>>(
 userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUserPublic>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getUsersControllerGetUserPublicQueryOptions(userId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * PATCH `/users/:userId/visibility` Update a user visibility (admin only)
 */
export const usersControllerUpdateUserVisibility = (
    userId: string,
    userPatchVisibilityDto: UserPatchVisibilityDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserAuthGetDto>> => {
    
    return axios.default.patch(
      `/api/users/${userId}/visibility`,
      userPatchVisibilityDto,options
    );
  }



export const getUsersControllerUpdateUserVisibilityMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerUpdateUserVisibility>>, TError,{userId: string;data: UserPatchVisibilityDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof usersControllerUpdateUserVisibility>>, TError,{userId: string;data: UserPatchVisibilityDto}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof usersControllerUpdateUserVisibility>>, {userId: string;data: UserPatchVisibilityDto}> = (props) => {
          const {userId,data} = props ?? {};

          return  usersControllerUpdateUserVisibility(userId,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UsersControllerUpdateUserVisibilityMutationResult = NonNullable<Awaited<ReturnType<typeof usersControllerUpdateUserVisibility>>>
    export type UsersControllerUpdateUserVisibilityMutationBody = UserPatchVisibilityDto
    export type UsersControllerUpdateUserVisibilityMutationError = AxiosError<unknown>

    export const useUsersControllerUpdateUserVisibility = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerUpdateUserVisibility>>, TError,{userId: string;data: UserPatchVisibilityDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof usersControllerUpdateUserVisibility>>,
        TError,
        {userId: string;data: UserPatchVisibilityDto},
        TContext
      > => {

      const mutationOptions = getUsersControllerUpdateUserVisibilityMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * GET `/users/email/:email` Check if a user exists (by email)
 */
export const usersControllerCheckEmail = (
    email: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserCheckEmailDto>> => {
    
    return axios.default.get(
      `/api/users/email/${email}`,options
    );
  }


export const getUsersControllerCheckEmailQueryKey = (email: string,) => {
    return [`/api/users/email/${email}`] as const;
    }

    
export const getUsersControllerCheckEmailQueryOptions = <TData = Awaited<ReturnType<typeof usersControllerCheckEmail>>, TError = AxiosError<unknown>>(email: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerCheckEmail>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersControllerCheckEmailQueryKey(email);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersControllerCheckEmail>>> = ({ signal }) => usersControllerCheckEmail(email, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(email), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usersControllerCheckEmail>>, TError, TData> & { queryKey: QueryKey }
}

export type UsersControllerCheckEmailQueryResult = NonNullable<Awaited<ReturnType<typeof usersControllerCheckEmail>>>
export type UsersControllerCheckEmailQueryError = AxiosError<unknown>


export function useUsersControllerCheckEmail<TData = Awaited<ReturnType<typeof usersControllerCheckEmail>>, TError = AxiosError<unknown>>(
 email: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerCheckEmail>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerCheckEmail>>,
          TError,
          TData
        > , 'initialData'
      >, axios?: AxiosRequestConfig}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useUsersControllerCheckEmail<TData = Awaited<ReturnType<typeof usersControllerCheckEmail>>, TError = AxiosError<unknown>>(
 email: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerCheckEmail>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerCheckEmail>>,
          TError,
          TData
        > , 'initialData'
      >, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useUsersControllerCheckEmail<TData = Awaited<ReturnType<typeof usersControllerCheckEmail>>, TError = AxiosError<unknown>>(
 email: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerCheckEmail>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }

export function useUsersControllerCheckEmail<TData = Awaited<ReturnType<typeof usersControllerCheckEmail>>, TError = AxiosError<unknown>>(
 email: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerCheckEmail>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getUsersControllerCheckEmailQueryOptions(email,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * POST `/users/:userId/role/:role` Add role to a user
 */
export const usersControllerAddUserRole = (
    userId: unknown,
    role: unknown,
    params: UsersControllerAddUserRoleParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserGetDto | UserAuthGetDto>> => {
    
    return axios.default.post(
      `/api/users/${userId}/role/${role}`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getUsersControllerAddUserRoleMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerAddUserRole>>, TError,{userId: unknown;role: unknown;params: UsersControllerAddUserRoleParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof usersControllerAddUserRole>>, TError,{userId: unknown;role: unknown;params: UsersControllerAddUserRoleParams}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof usersControllerAddUserRole>>, {userId: unknown;role: unknown;params: UsersControllerAddUserRoleParams}> = (props) => {
          const {userId,role,params} = props ?? {};

          return  usersControllerAddUserRole(userId,role,params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UsersControllerAddUserRoleMutationResult = NonNullable<Awaited<ReturnType<typeof usersControllerAddUserRole>>>
    
    export type UsersControllerAddUserRoleMutationError = AxiosError<unknown>

    export const useUsersControllerAddUserRole = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerAddUserRole>>, TError,{userId: unknown;role: unknown;params: UsersControllerAddUserRoleParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof usersControllerAddUserRole>>,
        TError,
        {userId: unknown;role: unknown;params: UsersControllerAddUserRoleParams},
        TContext
      > => {

      const mutationOptions = getUsersControllerAddUserRoleMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Delete `/users/:userId/role/:role` Remove role from a user
 */
export const usersControllerRmUserRole = (
    userId: unknown,
    role: unknown,
    params: UsersControllerRmUserRoleParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserGetDto>> => {
    
    return axios.default.delete(
      `/api/users/${userId}/role/${role}`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getUsersControllerRmUserRoleMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerRmUserRole>>, TError,{userId: unknown;role: unknown;params: UsersControllerRmUserRoleParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof usersControllerRmUserRole>>, TError,{userId: unknown;role: unknown;params: UsersControllerRmUserRoleParams}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof usersControllerRmUserRole>>, {userId: unknown;role: unknown;params: UsersControllerRmUserRoleParams}> = (props) => {
          const {userId,role,params} = props ?? {};

          return  usersControllerRmUserRole(userId,role,params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UsersControllerRmUserRoleMutationResult = NonNullable<Awaited<ReturnType<typeof usersControllerRmUserRole>>>
    
    export type UsersControllerRmUserRoleMutationError = AxiosError<unknown>

    export const useUsersControllerRmUserRole = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerRmUserRole>>, TError,{userId: unknown;role: unknown;params: UsersControllerRmUserRoleParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof usersControllerRmUserRole>>,
        TError,
        {userId: unknown;role: unknown;params: UsersControllerRmUserRoleParams},
        TContext
      > => {

      const mutationOptions = getUsersControllerRmUserRoleMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * POST `/users/:userId/avatar` Upload a user avatar
 * @summary Uploads a single file
 */
export const usersControllerUploadUserAvatar = (
    userId: string,
    usersControllerUploadUserAvatarBody: UsersControllerUploadUserAvatarBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserPublicGetDto | UserGetDto>> => {const formData = new FormData();
if(usersControllerUploadUserAvatarBody.file !== undefined) {
 formData.append('file', usersControllerUploadUserAvatarBody.file)
 }

    
    return axios.default.post(
      `/api/users/${userId}/avatar`,
      formData,options
    );
  }



export const getUsersControllerUploadUserAvatarMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerUploadUserAvatar>>, TError,{userId: string;data: UsersControllerUploadUserAvatarBody}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof usersControllerUploadUserAvatar>>, TError,{userId: string;data: UsersControllerUploadUserAvatarBody}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof usersControllerUploadUserAvatar>>, {userId: string;data: UsersControllerUploadUserAvatarBody}> = (props) => {
          const {userId,data} = props ?? {};

          return  usersControllerUploadUserAvatar(userId,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UsersControllerUploadUserAvatarMutationResult = NonNullable<Awaited<ReturnType<typeof usersControllerUploadUserAvatar>>>
    export type UsersControllerUploadUserAvatarMutationBody = UsersControllerUploadUserAvatarBody
    export type UsersControllerUploadUserAvatarMutationError = AxiosError<unknown>

    /**
 * @summary Uploads a single file
 */
export const useUsersControllerUploadUserAvatar = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerUploadUserAvatar>>, TError,{userId: string;data: UsersControllerUploadUserAvatarBody}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof usersControllerUploadUserAvatar>>,
        TError,
        {userId: string;data: UsersControllerUploadUserAvatarBody},
        TContext
      > => {

      const mutationOptions = getUsersControllerUploadUserAvatarMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * GET `/users/stats/metrics`
Get statistics about users
 */
export const usersControllerGetStatsByProgram = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserStatsGetDto>> => {
    
    return axios.default.get(
      `/api/users/stats/metrics`,options
    );
  }


export const getUsersControllerGetStatsByProgramQueryKey = () => {
    return [`/api/users/stats/metrics`] as const;
    }

    
export const getUsersControllerGetStatsByProgramQueryOptions = <TData = Awaited<ReturnType<typeof usersControllerGetStatsByProgram>>, TError = AxiosError<void>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetStatsByProgram>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersControllerGetStatsByProgramQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersControllerGetStatsByProgram>>> = ({ signal }) => usersControllerGetStatsByProgram({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetStatsByProgram>>, TError, TData> & { queryKey: QueryKey }
}

export type UsersControllerGetStatsByProgramQueryResult = NonNullable<Awaited<ReturnType<typeof usersControllerGetStatsByProgram>>>
export type UsersControllerGetStatsByProgramQueryError = AxiosError<void>


export function useUsersControllerGetStatsByProgram<TData = Awaited<ReturnType<typeof usersControllerGetStatsByProgram>>, TError = AxiosError<void>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetStatsByProgram>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetStatsByProgram>>,
          TError,
          TData
        > , 'initialData'
      >, axios?: AxiosRequestConfig}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useUsersControllerGetStatsByProgram<TData = Awaited<ReturnType<typeof usersControllerGetStatsByProgram>>, TError = AxiosError<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetStatsByProgram>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetStatsByProgram>>,
          TError,
          TData
        > , 'initialData'
      >, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useUsersControllerGetStatsByProgram<TData = Awaited<ReturnType<typeof usersControllerGetStatsByProgram>>, TError = AxiosError<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetStatsByProgram>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }

export function useUsersControllerGetStatsByProgram<TData = Awaited<ReturnType<typeof usersControllerGetStatsByProgram>>, TError = AxiosError<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetStatsByProgram>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getUsersControllerGetStatsByProgramQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * GET `/users/stats/graph/`
Get full time-series graph of users
 */
export const usersControllerGetGraph = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GraphGetDto[]>> => {
    
    return axios.default.get(
      `/api/users/stats/graph`,options
    );
  }


export const getUsersControllerGetGraphQueryKey = () => {
    return [`/api/users/stats/graph`] as const;
    }

    
export const getUsersControllerGetGraphQueryOptions = <TData = Awaited<ReturnType<typeof usersControllerGetGraph>>, TError = AxiosError<void>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetGraph>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersControllerGetGraphQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersControllerGetGraph>>> = ({ signal }) => usersControllerGetGraph({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetGraph>>, TError, TData> & { queryKey: QueryKey }
}

export type UsersControllerGetGraphQueryResult = NonNullable<Awaited<ReturnType<typeof usersControllerGetGraph>>>
export type UsersControllerGetGraphQueryError = AxiosError<void>


export function useUsersControllerGetGraph<TData = Awaited<ReturnType<typeof usersControllerGetGraph>>, TError = AxiosError<void>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetGraph>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetGraph>>,
          TError,
          TData
        > , 'initialData'
      >, axios?: AxiosRequestConfig}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useUsersControllerGetGraph<TData = Awaited<ReturnType<typeof usersControllerGetGraph>>, TError = AxiosError<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetGraph>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetGraph>>,
          TError,
          TData
        > , 'initialData'
      >, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useUsersControllerGetGraph<TData = Awaited<ReturnType<typeof usersControllerGetGraph>>, TError = AxiosError<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetGraph>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }

export function useUsersControllerGetGraph<TData = Awaited<ReturnType<typeof usersControllerGetGraph>>, TError = AxiosError<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetGraph>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getUsersControllerGetGraphQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const usersControllerCreateUser = (
    userCreateDto: UserCreateDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserGetDto>> => {
    
    return axios.default.post(
      `/api/users/create`,
      userCreateDto,options
    );
  }



export const getUsersControllerCreateUserMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerCreateUser>>, TError,{data: UserCreateDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof usersControllerCreateUser>>, TError,{data: UserCreateDto}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof usersControllerCreateUser>>, {data: UserCreateDto}> = (props) => {
          const {data} = props ?? {};

          return  usersControllerCreateUser(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UsersControllerCreateUserMutationResult = NonNullable<Awaited<ReturnType<typeof usersControllerCreateUser>>>
    export type UsersControllerCreateUserMutationBody = UserCreateDto
    export type UsersControllerCreateUserMutationError = AxiosError<unknown>

    export const useUsersControllerCreateUser = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerCreateUser>>, TError,{data: UserCreateDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof usersControllerCreateUser>>,
        TError,
        {data: UserCreateDto},
        TContext
      > => {

      const mutationOptions = getUsersControllerCreateUserMutationOptions(options);

      return useMutation(mutationOptions);
    }
    