/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Asteron
 * Novel writing tool
 * OpenAPI spec version: 1.0
 */
import {
  faker
} from '@faker-js/faker'
import {
  HttpResponse,
  delay,
  http
} from 'msw'
import type {
  CategoryGetDto
} from '.././models'

export const getCategoriesControllerGetAllResponseMock = (): CategoryGetDto[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({colour: faker.word.sample(), icon: faker.word.sample(), id: faker.word.sample(), name: faker.word.sample()})))

export const getCategoriesControllerGetCategoryResponseMock = (overrideResponse: Partial< CategoryGetDto > = {}): CategoryGetDto => ({colour: faker.word.sample(), icon: faker.word.sample(), id: faker.word.sample(), name: faker.word.sample(), ...overrideResponse})

export const getCategoriesControllerUpdateCategoryResponseMock = (overrideResponse: Partial< CategoryGetDto > = {}): CategoryGetDto => ({colour: faker.word.sample(), icon: faker.word.sample(), id: faker.word.sample(), name: faker.word.sample(), ...overrideResponse})

export const getCategoriesControllerDeleteCategoryResponseMock = (overrideResponse: Partial< CategoryGetDto > = {}): CategoryGetDto => ({colour: faker.word.sample(), icon: faker.word.sample(), id: faker.word.sample(), name: faker.word.sample(), ...overrideResponse})


export const getCategoriesControllerGetAllMockHandler = (overrideResponse?: CategoryGetDto[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<CategoryGetDto[]> | CategoryGetDto[])) => {
  return http.get('*/api/categories', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getCategoriesControllerGetAllResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getCategoriesControllerGetCategoryMockHandler = (overrideResponse?: CategoryGetDto | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<CategoryGetDto> | CategoryGetDto)) => {
  return http.get('*/api/categories/:categoryId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getCategoriesControllerGetCategoryResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getCategoriesControllerUpdateCategoryMockHandler = (overrideResponse?: CategoryGetDto | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<CategoryGetDto> | CategoryGetDto)) => {
  return http.patch('*/api/categories/:categoryId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getCategoriesControllerUpdateCategoryResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getCategoriesControllerDeleteCategoryMockHandler = (overrideResponse?: CategoryGetDto | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<CategoryGetDto> | CategoryGetDto)) => {
  return http.delete('*/api/categories/:categoryId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getCategoriesControllerDeleteCategoryResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}
export const getCategoriesMock = () => [
  getCategoriesControllerGetAllMockHandler(),
  getCategoriesControllerGetCategoryMockHandler(),
  getCategoriesControllerUpdateCategoryMockHandler(),
  getCategoriesControllerDeleteCategoryMockHandler()
]
