/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Asteron
 * Novel writing tool
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  CategoryGetDto,
  CategoryPatchDto
} from '.././models'



/**
 * GET `/categories` Get all my categories
 */
export const categoriesControllerGetAll = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CategoryGetDto[]>> => {
    
    return axios.default.get(
      `/api/categories`,options
    );
  }


export const getCategoriesControllerGetAllQueryKey = () => {
    return [`/api/categories`] as const;
    }

    
export const getCategoriesControllerGetAllQueryOptions = <TData = Awaited<ReturnType<typeof categoriesControllerGetAll>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof categoriesControllerGetAll>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCategoriesControllerGetAllQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof categoriesControllerGetAll>>> = ({ signal }) => categoriesControllerGetAll({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof categoriesControllerGetAll>>, TError, TData> & { queryKey: QueryKey }
}

export type CategoriesControllerGetAllQueryResult = NonNullable<Awaited<ReturnType<typeof categoriesControllerGetAll>>>
export type CategoriesControllerGetAllQueryError = AxiosError<unknown>


export function useCategoriesControllerGetAll<TData = Awaited<ReturnType<typeof categoriesControllerGetAll>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof categoriesControllerGetAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof categoriesControllerGetAll>>,
          TError,
          TData
        > , 'initialData'
      >, axios?: AxiosRequestConfig}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useCategoriesControllerGetAll<TData = Awaited<ReturnType<typeof categoriesControllerGetAll>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof categoriesControllerGetAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof categoriesControllerGetAll>>,
          TError,
          TData
        > , 'initialData'
      >, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useCategoriesControllerGetAll<TData = Awaited<ReturnType<typeof categoriesControllerGetAll>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof categoriesControllerGetAll>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }

export function useCategoriesControllerGetAll<TData = Awaited<ReturnType<typeof categoriesControllerGetAll>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof categoriesControllerGetAll>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getCategoriesControllerGetAllQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * GET `/categories/:categoryId` Get a single category's information
 */
export const categoriesControllerGetCategory = (
    categoryId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CategoryGetDto>> => {
    
    return axios.default.get(
      `/api/categories/${categoryId}`,options
    );
  }


export const getCategoriesControllerGetCategoryQueryKey = (categoryId: string,) => {
    return [`/api/categories/${categoryId}`] as const;
    }

    
export const getCategoriesControllerGetCategoryQueryOptions = <TData = Awaited<ReturnType<typeof categoriesControllerGetCategory>>, TError = AxiosError<void>>(categoryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof categoriesControllerGetCategory>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCategoriesControllerGetCategoryQueryKey(categoryId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof categoriesControllerGetCategory>>> = ({ signal }) => categoriesControllerGetCategory(categoryId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(categoryId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof categoriesControllerGetCategory>>, TError, TData> & { queryKey: QueryKey }
}

export type CategoriesControllerGetCategoryQueryResult = NonNullable<Awaited<ReturnType<typeof categoriesControllerGetCategory>>>
export type CategoriesControllerGetCategoryQueryError = AxiosError<void>


export function useCategoriesControllerGetCategory<TData = Awaited<ReturnType<typeof categoriesControllerGetCategory>>, TError = AxiosError<void>>(
 categoryId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof categoriesControllerGetCategory>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof categoriesControllerGetCategory>>,
          TError,
          TData
        > , 'initialData'
      >, axios?: AxiosRequestConfig}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useCategoriesControllerGetCategory<TData = Awaited<ReturnType<typeof categoriesControllerGetCategory>>, TError = AxiosError<void>>(
 categoryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof categoriesControllerGetCategory>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof categoriesControllerGetCategory>>,
          TError,
          TData
        > , 'initialData'
      >, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useCategoriesControllerGetCategory<TData = Awaited<ReturnType<typeof categoriesControllerGetCategory>>, TError = AxiosError<void>>(
 categoryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof categoriesControllerGetCategory>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }

export function useCategoriesControllerGetCategory<TData = Awaited<ReturnType<typeof categoriesControllerGetCategory>>, TError = AxiosError<void>>(
 categoryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof categoriesControllerGetCategory>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getCategoriesControllerGetCategoryQueryOptions(categoryId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * PATCH `/categories/:categoryId` Update a category (mine or admin only)
 */
export const categoriesControllerUpdateCategory = (
    categoryId: string,
    categoryPatchDto: CategoryPatchDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CategoryGetDto>> => {
    
    return axios.default.patch(
      `/api/categories/${categoryId}`,
      categoryPatchDto,options
    );
  }



export const getCategoriesControllerUpdateCategoryMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof categoriesControllerUpdateCategory>>, TError,{categoryId: string;data: CategoryPatchDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof categoriesControllerUpdateCategory>>, TError,{categoryId: string;data: CategoryPatchDto}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof categoriesControllerUpdateCategory>>, {categoryId: string;data: CategoryPatchDto}> = (props) => {
          const {categoryId,data} = props ?? {};

          return  categoriesControllerUpdateCategory(categoryId,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CategoriesControllerUpdateCategoryMutationResult = NonNullable<Awaited<ReturnType<typeof categoriesControllerUpdateCategory>>>
    export type CategoriesControllerUpdateCategoryMutationBody = CategoryPatchDto
    export type CategoriesControllerUpdateCategoryMutationError = AxiosError<unknown>

    export const useCategoriesControllerUpdateCategory = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof categoriesControllerUpdateCategory>>, TError,{categoryId: string;data: CategoryPatchDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof categoriesControllerUpdateCategory>>,
        TError,
        {categoryId: string;data: CategoryPatchDto},
        TContext
      > => {

      const mutationOptions = getCategoriesControllerUpdateCategoryMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * DELETE `/categories/:categoryId` Delete a category
 */
export const categoriesControllerDeleteCategory = (
    categoryId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CategoryGetDto>> => {
    
    return axios.default.delete(
      `/api/categories/${categoryId}`,options
    );
  }



export const getCategoriesControllerDeleteCategoryMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof categoriesControllerDeleteCategory>>, TError,{categoryId: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof categoriesControllerDeleteCategory>>, TError,{categoryId: string}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof categoriesControllerDeleteCategory>>, {categoryId: string}> = (props) => {
          const {categoryId} = props ?? {};

          return  categoriesControllerDeleteCategory(categoryId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CategoriesControllerDeleteCategoryMutationResult = NonNullable<Awaited<ReturnType<typeof categoriesControllerDeleteCategory>>>
    
    export type CategoriesControllerDeleteCategoryMutationError = AxiosError<unknown>

    export const useCategoriesControllerDeleteCategory = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof categoriesControllerDeleteCategory>>, TError,{categoryId: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof categoriesControllerDeleteCategory>>,
        TError,
        {categoryId: string},
        TContext
      > => {

      const mutationOptions = getCategoriesControllerDeleteCategoryMutationOptions(options);

      return useMutation(mutationOptions);
    }
    