/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Asteron
 * Novel writing tool
 * OpenAPI spec version: 1.0
 */
import {
  faker
} from '@faker-js/faker'
import {
  HttpResponse,
  delay,
  http
} from 'msw'
import type {
  ElementGetDto
} from '.././models'

export const getElementsControllerGetAllResponseMock = (): ElementGetDto[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({collections: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.word.sample())), colour: faker.word.sample(), defaultName: faker.word.sample(), id: faker.word.sample(), image: faker.word.sample(), names: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({})), timestamp: `${faker.date.past().toISOString().split('.')[0]}Z`})))

export const getElementsControllerGetMyElementResponseMock = (): ElementGetDto[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({collections: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.word.sample())), colour: faker.word.sample(), defaultName: faker.word.sample(), id: faker.word.sample(), image: faker.word.sample(), names: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({})), timestamp: `${faker.date.past().toISOString().split('.')[0]}Z`})))

export const getElementsControllerGetElementResponseMock = (overrideResponse: Partial< ElementGetDto > = {}): ElementGetDto => ({collections: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.word.sample())), colour: faker.word.sample(), defaultName: faker.word.sample(), id: faker.word.sample(), image: faker.word.sample(), names: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({})), timestamp: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse})

export const getElementsControllerUpdateElementResponseMock = (overrideResponse: Partial< ElementGetDto > = {}): ElementGetDto => ({collections: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.word.sample())), colour: faker.word.sample(), defaultName: faker.word.sample(), id: faker.word.sample(), image: faker.word.sample(), names: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({})), timestamp: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse})

export const getElementsControllerDeleteElementResponseMock = (overrideResponse: Partial< ElementGetDto > = {}): ElementGetDto => ({collections: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.word.sample())), colour: faker.word.sample(), defaultName: faker.word.sample(), id: faker.word.sample(), image: faker.word.sample(), names: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({})), timestamp: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse})

export const getElementsControllerCreateElementResponseMock = (overrideResponse: Partial< ElementGetDto > = {}): ElementGetDto => ({collections: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.word.sample())), colour: faker.word.sample(), defaultName: faker.word.sample(), id: faker.word.sample(), image: faker.word.sample(), names: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({})), timestamp: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse})


export const getElementsControllerGetAllMockHandler = (overrideResponse?: ElementGetDto[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ElementGetDto[]> | ElementGetDto[])) => {
  return http.get('*/api/element', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getElementsControllerGetAllResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getElementsControllerGetMyElementMockHandler = (overrideResponse?: ElementGetDto[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ElementGetDto[]> | ElementGetDto[])) => {
  return http.get('*/api/element/mine', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getElementsControllerGetMyElementResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getElementsControllerGetElementMockHandler = (overrideResponse?: ElementGetDto | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ElementGetDto> | ElementGetDto)) => {
  return http.get('*/api/element/:collectionId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getElementsControllerGetElementResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getElementsControllerUpdateElementMockHandler = (overrideResponse?: ElementGetDto | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<ElementGetDto> | ElementGetDto)) => {
  return http.patch('*/api/element/:collectionId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getElementsControllerUpdateElementResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getElementsControllerDeleteElementMockHandler = (overrideResponse?: ElementGetDto | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<ElementGetDto> | ElementGetDto)) => {
  return http.delete('*/api/element/:collectionId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getElementsControllerDeleteElementResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getElementsControllerCreateElementMockHandler = (overrideResponse?: ElementGetDto | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ElementGetDto> | ElementGetDto)) => {
  return http.post('*/api/element/create', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getElementsControllerCreateElementResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}
export const getElementsMock = () => [
  getElementsControllerGetAllMockHandler(),
  getElementsControllerGetMyElementMockHandler(),
  getElementsControllerGetElementMockHandler(),
  getElementsControllerUpdateElementMockHandler(),
  getElementsControllerDeleteElementMockHandler(),
  getElementsControllerCreateElementMockHandler()
]
