/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Asteron
 * Novel writing tool
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  ElementCreateDto,
  ElementGetDto,
  ElementPatchDto
} from '.././models'



/**
 * GET `/element` Get all element
 */
export const elementsControllerGetAll = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ElementGetDto[]>> => {
    
    return axios.default.get(
      `/api/element`,options
    );
  }


export const getElementsControllerGetAllQueryKey = () => {
    return [`/api/element`] as const;
    }

    
export const getElementsControllerGetAllQueryOptions = <TData = Awaited<ReturnType<typeof elementsControllerGetAll>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof elementsControllerGetAll>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getElementsControllerGetAllQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof elementsControllerGetAll>>> = ({ signal }) => elementsControllerGetAll({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof elementsControllerGetAll>>, TError, TData> & { queryKey: QueryKey }
}

export type ElementsControllerGetAllQueryResult = NonNullable<Awaited<ReturnType<typeof elementsControllerGetAll>>>
export type ElementsControllerGetAllQueryError = AxiosError<unknown>


export function useElementsControllerGetAll<TData = Awaited<ReturnType<typeof elementsControllerGetAll>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof elementsControllerGetAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof elementsControllerGetAll>>,
          TError,
          TData
        > , 'initialData'
      >, axios?: AxiosRequestConfig}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useElementsControllerGetAll<TData = Awaited<ReturnType<typeof elementsControllerGetAll>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof elementsControllerGetAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof elementsControllerGetAll>>,
          TError,
          TData
        > , 'initialData'
      >, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useElementsControllerGetAll<TData = Awaited<ReturnType<typeof elementsControllerGetAll>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof elementsControllerGetAll>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }

export function useElementsControllerGetAll<TData = Awaited<ReturnType<typeof elementsControllerGetAll>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof elementsControllerGetAll>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getElementsControllerGetAllQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * GET `/element/mine` Get my element
 */
export const elementsControllerGetMyElement = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ElementGetDto[]>> => {
    
    return axios.default.get(
      `/api/element/mine`,options
    );
  }


export const getElementsControllerGetMyElementQueryKey = () => {
    return [`/api/element/mine`] as const;
    }

    
export const getElementsControllerGetMyElementQueryOptions = <TData = Awaited<ReturnType<typeof elementsControllerGetMyElement>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof elementsControllerGetMyElement>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getElementsControllerGetMyElementQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof elementsControllerGetMyElement>>> = ({ signal }) => elementsControllerGetMyElement({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof elementsControllerGetMyElement>>, TError, TData> & { queryKey: QueryKey }
}

export type ElementsControllerGetMyElementQueryResult = NonNullable<Awaited<ReturnType<typeof elementsControllerGetMyElement>>>
export type ElementsControllerGetMyElementQueryError = AxiosError<unknown>


export function useElementsControllerGetMyElement<TData = Awaited<ReturnType<typeof elementsControllerGetMyElement>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof elementsControllerGetMyElement>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof elementsControllerGetMyElement>>,
          TError,
          TData
        > , 'initialData'
      >, axios?: AxiosRequestConfig}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useElementsControllerGetMyElement<TData = Awaited<ReturnType<typeof elementsControllerGetMyElement>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof elementsControllerGetMyElement>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof elementsControllerGetMyElement>>,
          TError,
          TData
        > , 'initialData'
      >, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useElementsControllerGetMyElement<TData = Awaited<ReturnType<typeof elementsControllerGetMyElement>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof elementsControllerGetMyElement>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }

export function useElementsControllerGetMyElement<TData = Awaited<ReturnType<typeof elementsControllerGetMyElement>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof elementsControllerGetMyElement>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getElementsControllerGetMyElementQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * GET `/element/:collectionId` Get a single collection's information
 */
export const elementsControllerGetElement = (
    collectionId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ElementGetDto>> => {
    
    return axios.default.get(
      `/api/element/${collectionId}`,options
    );
  }


export const getElementsControllerGetElementQueryKey = (collectionId: string,) => {
    return [`/api/element/${collectionId}`] as const;
    }

    
export const getElementsControllerGetElementQueryOptions = <TData = Awaited<ReturnType<typeof elementsControllerGetElement>>, TError = AxiosError<void>>(collectionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof elementsControllerGetElement>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getElementsControllerGetElementQueryKey(collectionId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof elementsControllerGetElement>>> = ({ signal }) => elementsControllerGetElement(collectionId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(collectionId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof elementsControllerGetElement>>, TError, TData> & { queryKey: QueryKey }
}

export type ElementsControllerGetElementQueryResult = NonNullable<Awaited<ReturnType<typeof elementsControllerGetElement>>>
export type ElementsControllerGetElementQueryError = AxiosError<void>


export function useElementsControllerGetElement<TData = Awaited<ReturnType<typeof elementsControllerGetElement>>, TError = AxiosError<void>>(
 collectionId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof elementsControllerGetElement>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof elementsControllerGetElement>>,
          TError,
          TData
        > , 'initialData'
      >, axios?: AxiosRequestConfig}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useElementsControllerGetElement<TData = Awaited<ReturnType<typeof elementsControllerGetElement>>, TError = AxiosError<void>>(
 collectionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof elementsControllerGetElement>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof elementsControllerGetElement>>,
          TError,
          TData
        > , 'initialData'
      >, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useElementsControllerGetElement<TData = Awaited<ReturnType<typeof elementsControllerGetElement>>, TError = AxiosError<void>>(
 collectionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof elementsControllerGetElement>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }

export function useElementsControllerGetElement<TData = Awaited<ReturnType<typeof elementsControllerGetElement>>, TError = AxiosError<void>>(
 collectionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof elementsControllerGetElement>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getElementsControllerGetElementQueryOptions(collectionId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * PATCH `/element/:collectionId` Update a collection (mine or admin only)
 */
export const elementsControllerUpdateElement = (
    collectionId: string,
    elementPatchDto: ElementPatchDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ElementGetDto>> => {
    
    return axios.default.patch(
      `/api/element/${collectionId}`,
      elementPatchDto,options
    );
  }



export const getElementsControllerUpdateElementMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof elementsControllerUpdateElement>>, TError,{collectionId: string;data: ElementPatchDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof elementsControllerUpdateElement>>, TError,{collectionId: string;data: ElementPatchDto}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof elementsControllerUpdateElement>>, {collectionId: string;data: ElementPatchDto}> = (props) => {
          const {collectionId,data} = props ?? {};

          return  elementsControllerUpdateElement(collectionId,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ElementsControllerUpdateElementMutationResult = NonNullable<Awaited<ReturnType<typeof elementsControllerUpdateElement>>>
    export type ElementsControllerUpdateElementMutationBody = ElementPatchDto
    export type ElementsControllerUpdateElementMutationError = AxiosError<unknown>

    export const useElementsControllerUpdateElement = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof elementsControllerUpdateElement>>, TError,{collectionId: string;data: ElementPatchDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof elementsControllerUpdateElement>>,
        TError,
        {collectionId: string;data: ElementPatchDto},
        TContext
      > => {

      const mutationOptions = getElementsControllerUpdateElementMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * DELETE `/element/:collectionId` Delete a collection
 */
export const elementsControllerDeleteElement = (
    collectionId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ElementGetDto>> => {
    
    return axios.default.delete(
      `/api/element/${collectionId}`,options
    );
  }



export const getElementsControllerDeleteElementMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof elementsControllerDeleteElement>>, TError,{collectionId: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof elementsControllerDeleteElement>>, TError,{collectionId: string}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof elementsControllerDeleteElement>>, {collectionId: string}> = (props) => {
          const {collectionId} = props ?? {};

          return  elementsControllerDeleteElement(collectionId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ElementsControllerDeleteElementMutationResult = NonNullable<Awaited<ReturnType<typeof elementsControllerDeleteElement>>>
    
    export type ElementsControllerDeleteElementMutationError = AxiosError<unknown>

    export const useElementsControllerDeleteElement = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof elementsControllerDeleteElement>>, TError,{collectionId: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof elementsControllerDeleteElement>>,
        TError,
        {collectionId: string},
        TContext
      > => {

      const mutationOptions = getElementsControllerDeleteElementMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * POST `/element/create`
Create a collection in our backend, (NOT) in the Firebase
Please be careful with this API call
(though the Firebase collection creation happends automatically when they first log in)
 */
export const elementsControllerCreateElement = (
    elementCreateDto: ElementCreateDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ElementGetDto>> => {
    
    return axios.default.post(
      `/api/element/create`,
      elementCreateDto,options
    );
  }



export const getElementsControllerCreateElementMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof elementsControllerCreateElement>>, TError,{data: ElementCreateDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof elementsControllerCreateElement>>, TError,{data: ElementCreateDto}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof elementsControllerCreateElement>>, {data: ElementCreateDto}> = (props) => {
          const {data} = props ?? {};

          return  elementsControllerCreateElement(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ElementsControllerCreateElementMutationResult = NonNullable<Awaited<ReturnType<typeof elementsControllerCreateElement>>>
    export type ElementsControllerCreateElementMutationBody = ElementCreateDto
    export type ElementsControllerCreateElementMutationError = AxiosError<unknown>

    export const useElementsControllerCreateElement = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof elementsControllerCreateElement>>, TError,{data: ElementCreateDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof elementsControllerCreateElement>>,
        TError,
        {data: ElementCreateDto},
        TContext
      > => {

      const mutationOptions = getElementsControllerCreateElementMutationOptions(options);

      return useMutation(mutationOptions);
    }
    